// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `oauth.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct MigrationPayload {
    // message fields
    pub otp_parameters: ::protobuf::RepeatedField<OtpParameters>,
    pub version: i32,
    pub batch_size: i32,
    pub batch_index: i32,
    pub batch_id: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a MigrationPayload {
    fn default() -> &'a MigrationPayload {
        <MigrationPayload as ::protobuf::Message>::default_instance()
    }
}

impl MigrationPayload {
    pub fn new() -> MigrationPayload {
        ::std::default::Default::default()
    }

    // repeated .protobuf.oauth.OtpParameters otp_parameters = 1;


    pub fn get_otp_parameters(&self) -> &[OtpParameters] {
        &self.otp_parameters
    }
    pub fn clear_otp_parameters(&mut self) {
        self.otp_parameters.clear();
    }

    // Param is passed by value, moved
    pub fn set_otp_parameters(&mut self, v: ::protobuf::RepeatedField<OtpParameters>) {
        self.otp_parameters = v;
    }

    // Mutable pointer to the field.
    pub fn mut_otp_parameters(&mut self) -> &mut ::protobuf::RepeatedField<OtpParameters> {
        &mut self.otp_parameters
    }

    // Take field
    pub fn take_otp_parameters(&mut self) -> ::protobuf::RepeatedField<OtpParameters> {
        ::std::mem::replace(&mut self.otp_parameters, ::protobuf::RepeatedField::new())
    }

    // int32 version = 2;


    pub fn get_version(&self) -> i32 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i32) {
        self.version = v;
    }

    // int32 batch_size = 3;


    pub fn get_batch_size(&self) -> i32 {
        self.batch_size
    }
    pub fn clear_batch_size(&mut self) {
        self.batch_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_batch_size(&mut self, v: i32) {
        self.batch_size = v;
    }

    // int32 batch_index = 4;


    pub fn get_batch_index(&self) -> i32 {
        self.batch_index
    }
    pub fn clear_batch_index(&mut self) {
        self.batch_index = 0;
    }

    // Param is passed by value, moved
    pub fn set_batch_index(&mut self, v: i32) {
        self.batch_index = v;
    }

    // int32 batch_id = 5;


    pub fn get_batch_id(&self) -> i32 {
        self.batch_id
    }
    pub fn clear_batch_id(&mut self) {
        self.batch_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_batch_id(&mut self, v: i32) {
        self.batch_id = v;
    }
}

impl ::protobuf::Message for MigrationPayload {
    fn is_initialized(&self) -> bool {
        for v in &self.otp_parameters {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.otp_parameters)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.version = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.batch_size = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.batch_index = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.batch_id = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.otp_parameters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(2, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.batch_size != 0 {
            my_size += ::protobuf::rt::value_size(3, self.batch_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.batch_index != 0 {
            my_size += ::protobuf::rt::value_size(4, self.batch_index, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.batch_id != 0 {
            my_size += ::protobuf::rt::value_size(5, self.batch_id, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.otp_parameters {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        if self.version != 0 {
            os.write_int32(2, self.version)?;
        }
        if self.batch_size != 0 {
            os.write_int32(3, self.batch_size)?;
        }
        if self.batch_index != 0 {
            os.write_int32(4, self.batch_index)?;
        }
        if self.batch_id != 0 {
            os.write_int32(5, self.batch_id)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> MigrationPayload {
        MigrationPayload::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<OtpParameters>>(
                "otp_parameters",
                |m: &MigrationPayload| { &m.otp_parameters },
                |m: &mut MigrationPayload| { &mut m.otp_parameters },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "version",
                |m: &MigrationPayload| { &m.version },
                |m: &mut MigrationPayload| { &mut m.version },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "batch_size",
                |m: &MigrationPayload| { &m.batch_size },
                |m: &mut MigrationPayload| { &mut m.batch_size },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "batch_index",
                |m: &MigrationPayload| { &m.batch_index },
                |m: &mut MigrationPayload| { &mut m.batch_index },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "batch_id",
                |m: &MigrationPayload| { &m.batch_id },
                |m: &mut MigrationPayload| { &mut m.batch_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<MigrationPayload>(
                "MigrationPayload",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static MigrationPayload {
        static instance: ::protobuf::rt::LazyV2<MigrationPayload> = ::protobuf::rt::LazyV2::INIT;
        instance.get(MigrationPayload::new)
    }
}

impl ::protobuf::Clear for MigrationPayload {
    fn clear(&mut self) {
        self.otp_parameters.clear();
        self.version = 0;
        self.batch_size = 0;
        self.batch_index = 0;
        self.batch_id = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for MigrationPayload {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for MigrationPayload {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct OtpParameters {
    // message fields
    pub secret: ::std::vec::Vec<u8>,
    pub name: ::std::string::String,
    pub issuer: ::std::string::String,
    pub algorithm: Algorithm,
    pub digits: DigitCount,
    pub field_type: OtpType,
    pub counter: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OtpParameters {
    fn default() -> &'a OtpParameters {
        <OtpParameters as ::protobuf::Message>::default_instance()
    }
}

impl OtpParameters {
    pub fn new() -> OtpParameters {
        ::std::default::Default::default()
    }

    // bytes secret = 1;


    pub fn get_secret(&self) -> &[u8] {
        &self.secret
    }
    pub fn clear_secret(&mut self) {
        self.secret.clear();
    }

    // Param is passed by value, moved
    pub fn set_secret(&mut self, v: ::std::vec::Vec<u8>) {
        self.secret = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_secret(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.secret
    }

    // Take field
    pub fn take_secret(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.secret, ::std::vec::Vec::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // string issuer = 3;


    pub fn get_issuer(&self) -> &str {
        &self.issuer
    }
    pub fn clear_issuer(&mut self) {
        self.issuer.clear();
    }

    // Param is passed by value, moved
    pub fn set_issuer(&mut self, v: ::std::string::String) {
        self.issuer = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_issuer(&mut self) -> &mut ::std::string::String {
        &mut self.issuer
    }

    // Take field
    pub fn take_issuer(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.issuer, ::std::string::String::new())
    }

    // .protobuf.oauth.Algorithm algorithm = 4;


    pub fn get_algorithm(&self) -> Algorithm {
        self.algorithm
    }
    pub fn clear_algorithm(&mut self) {
        self.algorithm = Algorithm::ALGORITHM_TYPE_UNSPECIFIED;
    }

    // Param is passed by value, moved
    pub fn set_algorithm(&mut self, v: Algorithm) {
        self.algorithm = v;
    }

    // .protobuf.oauth.DigitCount digits = 5;


    pub fn get_digits(&self) -> DigitCount {
        self.digits
    }
    pub fn clear_digits(&mut self) {
        self.digits = DigitCount::DIGIT_COUNT_UNSPECIFIED;
    }

    // Param is passed by value, moved
    pub fn set_digits(&mut self, v: DigitCount) {
        self.digits = v;
    }

    // .protobuf.oauth.OtpType type = 6;


    pub fn get_field_type(&self) -> OtpType {
        self.field_type
    }
    pub fn clear_field_type(&mut self) {
        self.field_type = OtpType::OTP_TYPE_UNSPECIFIED;
    }

    // Param is passed by value, moved
    pub fn set_field_type(&mut self, v: OtpType) {
        self.field_type = v;
    }

    // int64 counter = 7;


    pub fn get_counter(&self) -> i64 {
        self.counter
    }
    pub fn clear_counter(&mut self) {
        self.counter = 0;
    }

    // Param is passed by value, moved
    pub fn set_counter(&mut self, v: i64) {
        self.counter = v;
    }
}

impl ::protobuf::Message for OtpParameters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.secret)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.issuer)?;
                },
                4 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.algorithm, 4, &mut self.unknown_fields)?
                },
                5 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.digits, 5, &mut self.unknown_fields)?
                },
                6 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.field_type, 6, &mut self.unknown_fields)?
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.counter = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.secret.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.secret);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.issuer.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.issuer);
        }
        if self.algorithm != Algorithm::ALGORITHM_TYPE_UNSPECIFIED {
            my_size += ::protobuf::rt::enum_size(4, self.algorithm);
        }
        if self.digits != DigitCount::DIGIT_COUNT_UNSPECIFIED {
            my_size += ::protobuf::rt::enum_size(5, self.digits);
        }
        if self.field_type != OtpType::OTP_TYPE_UNSPECIFIED {
            my_size += ::protobuf::rt::enum_size(6, self.field_type);
        }
        if self.counter != 0 {
            my_size += ::protobuf::rt::value_size(7, self.counter, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.secret.is_empty() {
            os.write_bytes(1, &self.secret)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.issuer.is_empty() {
            os.write_string(3, &self.issuer)?;
        }
        if self.algorithm != Algorithm::ALGORITHM_TYPE_UNSPECIFIED {
            os.write_enum(4, ::protobuf::ProtobufEnum::value(&self.algorithm))?;
        }
        if self.digits != DigitCount::DIGIT_COUNT_UNSPECIFIED {
            os.write_enum(5, ::protobuf::ProtobufEnum::value(&self.digits))?;
        }
        if self.field_type != OtpType::OTP_TYPE_UNSPECIFIED {
            os.write_enum(6, ::protobuf::ProtobufEnum::value(&self.field_type))?;
        }
        if self.counter != 0 {
            os.write_int64(7, self.counter)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OtpParameters {
        OtpParameters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "secret",
                |m: &OtpParameters| { &m.secret },
                |m: &mut OtpParameters| { &mut m.secret },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &OtpParameters| { &m.name },
                |m: &mut OtpParameters| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "issuer",
                |m: &OtpParameters| { &m.issuer },
                |m: &mut OtpParameters| { &mut m.issuer },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<Algorithm>>(
                "algorithm",
                |m: &OtpParameters| { &m.algorithm },
                |m: &mut OtpParameters| { &mut m.algorithm },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<DigitCount>>(
                "digits",
                |m: &OtpParameters| { &m.digits },
                |m: &mut OtpParameters| { &mut m.digits },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<OtpType>>(
                "type",
                |m: &OtpParameters| { &m.field_type },
                |m: &mut OtpParameters| { &mut m.field_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "counter",
                |m: &OtpParameters| { &m.counter },
                |m: &mut OtpParameters| { &mut m.counter },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<OtpParameters>(
                "OtpParameters",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static OtpParameters {
        static instance: ::protobuf::rt::LazyV2<OtpParameters> = ::protobuf::rt::LazyV2::INIT;
        instance.get(OtpParameters::new)
    }
}

impl ::protobuf::Clear for OtpParameters {
    fn clear(&mut self) {
        self.secret.clear();
        self.name.clear();
        self.issuer.clear();
        self.algorithm = Algorithm::ALGORITHM_TYPE_UNSPECIFIED;
        self.digits = DigitCount::DIGIT_COUNT_UNSPECIFIED;
        self.field_type = OtpType::OTP_TYPE_UNSPECIFIED;
        self.counter = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OtpParameters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OtpParameters {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum Algorithm {
    ALGORITHM_TYPE_UNSPECIFIED = 0,
    SHA1 = 1,
    SHA256 = 2,
    SHA512 = 3,
    MD5 = 4,
}

impl ::protobuf::ProtobufEnum for Algorithm {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Algorithm> {
        match value {
            0 => ::std::option::Option::Some(Algorithm::ALGORITHM_TYPE_UNSPECIFIED),
            1 => ::std::option::Option::Some(Algorithm::SHA1),
            2 => ::std::option::Option::Some(Algorithm::SHA256),
            3 => ::std::option::Option::Some(Algorithm::SHA512),
            4 => ::std::option::Option::Some(Algorithm::MD5),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [Algorithm] = &[
            Algorithm::ALGORITHM_TYPE_UNSPECIFIED,
            Algorithm::SHA1,
            Algorithm::SHA256,
            Algorithm::SHA512,
            Algorithm::MD5,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<Algorithm>("Algorithm", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for Algorithm {
}

impl ::std::default::Default for Algorithm {
    fn default() -> Self {
        Algorithm::ALGORITHM_TYPE_UNSPECIFIED
    }
}

impl ::protobuf::reflect::ProtobufValue for Algorithm {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum DigitCount {
    DIGIT_COUNT_UNSPECIFIED = 0,
    SIX = 1,
    EIGHT = 2,
}

impl ::protobuf::ProtobufEnum for DigitCount {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<DigitCount> {
        match value {
            0 => ::std::option::Option::Some(DigitCount::DIGIT_COUNT_UNSPECIFIED),
            1 => ::std::option::Option::Some(DigitCount::SIX),
            2 => ::std::option::Option::Some(DigitCount::EIGHT),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [DigitCount] = &[
            DigitCount::DIGIT_COUNT_UNSPECIFIED,
            DigitCount::SIX,
            DigitCount::EIGHT,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<DigitCount>("DigitCount", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for DigitCount {
}

impl ::std::default::Default for DigitCount {
    fn default() -> Self {
        DigitCount::DIGIT_COUNT_UNSPECIFIED
    }
}

impl ::protobuf::reflect::ProtobufValue for DigitCount {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum OtpType {
    OTP_TYPE_UNSPECIFIED = 0,
    HOTP = 1,
    TOTP = 2,
}

impl ::protobuf::ProtobufEnum for OtpType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<OtpType> {
        match value {
            0 => ::std::option::Option::Some(OtpType::OTP_TYPE_UNSPECIFIED),
            1 => ::std::option::Option::Some(OtpType::HOTP),
            2 => ::std::option::Option::Some(OtpType::TOTP),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [OtpType] = &[
            OtpType::OTP_TYPE_UNSPECIFIED,
            OtpType::HOTP,
            OtpType::TOTP,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<OtpType>("OtpType", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for OtpType {
}

impl ::std::default::Default for OtpType {
    fn default() -> Self {
        OtpType::OTP_TYPE_UNSPECIFIED
    }
}

impl ::protobuf::reflect::ProtobufValue for OtpType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0boauth.proto\x12\x0eprotobuf.oauth\"\xcd\x01\n\x10MigrationPayload\
    \x12D\n\x0eotp_parameters\x18\x01\x20\x03(\x0b2\x1d.protobuf.oauth.OtpPa\
    rametersR\rotpParameters\x12\x18\n\x07version\x18\x02\x20\x01(\x05R\x07v\
    ersion\x12\x1d\n\nbatch_size\x18\x03\x20\x01(\x05R\tbatchSize\x12\x1f\n\
    \x0bbatch_index\x18\x04\x20\x01(\x05R\nbatchIndex\x12\x19\n\x08batch_id\
    \x18\x05\x20\x01(\x05R\x07batchId\"\x87\x02\n\rOtpParameters\x12\x16\n\
    \x06secret\x18\x01\x20\x01(\x0cR\x06secret\x12\x12\n\x04name\x18\x02\x20\
    \x01(\tR\x04name\x12\x16\n\x06issuer\x18\x03\x20\x01(\tR\x06issuer\x127\
    \n\talgorithm\x18\x04\x20\x01(\x0e2\x19.protobuf.oauth.AlgorithmR\talgor\
    ithm\x122\n\x06digits\x18\x05\x20\x01(\x0e2\x1a.protobuf.oauth.DigitCoun\
    tR\x06digits\x12+\n\x04type\x18\x06\x20\x01(\x0e2\x17.protobuf.oauth.Otp\
    TypeR\x04type\x12\x18\n\x07counter\x18\x07\x20\x01(\x03R\x07counter*V\n\
    \tAlgorithm\x12\x1e\n\x1aALGORITHM_TYPE_UNSPECIFIED\x10\0\x12\x08\n\x04S\
    HA1\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\n\n\x06SHA512\x10\x03\x12\x07\
    \n\x03MD5\x10\x04*=\n\nDigitCount\x12\x1b\n\x17DIGIT_COUNT_UNSPECIFIED\
    \x10\0\x12\x07\n\x03SIX\x10\x01\x12\t\n\x05EIGHT\x10\x02*7\n\x07OtpType\
    \x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\0\x12\x08\n\x04HOTP\x10\x01\x12\
    \x08\n\x04TOTP\x10\x02b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
